spring:
  application:
    name: shopConsumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
server:
  port: 1211

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
# end::configuration-eureka[]
  endpoint:
    health:
      show-details: ALWAYS
